repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9030
    hooks:
      - id: style-files
      - id: parsable-R
      - id: no-browser-statement
      - id: no-debug-statement
      - id: readme-rmd-rendered
      - id: use-tidy-description

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
